"""Split the generated course corpus into the data each page actually needs."""

import json
from pathlib import Path

DATA = Path(__file__).resolve().parent.parent / "data"
source = (DATA / "learning-data.js").read_text(encoding="utf-8")
prefix = "window.MANCHAI_DATA="
if prefix not in source:
    raise ValueError("Unexpected learning-data.js format")
corpus = json.loads(source.split(prefix, 1)[1].rstrip(";\n"))
if len(corpus["words"]) < 400_000 or len(corpus["chapters"]) != 20:
    raise ValueError("Learning corpus is incomplete")

CHUNK_SIZE = 10_000


def write(name, global_name, payload):
    (DATA / name).write_text(
        "// Generated by tools/build-runtime-data.py from data/learning-data.js.\n"
        + f"window.{global_name}="
        + json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
        + ";\n",
        encoding="utf-8",
    )


write("lesson-data.js", "MANCHAI_DATA", {
    "chapters": corpus["chapters"],
    "candidates": corpus["candidates"],
})
write("code-data.js", "MANCHAI_DATA", {
    "codes": corpus["codes"],
    "candidates": corpus["candidates"],
    "wordCount": len(corpus["words"]),
    "vocabChunkSize": CHUNK_SIZE,
})
for old in DATA.glob("vocab-part-*.js"):
    old.unlink()
(DATA / "vocab-data.js").unlink(missing_ok=True)
for index, start in enumerate(range(0, len(corpus["words"]), CHUNK_SIZE)):
    payload = {"words": corpus["words"][start:start + CHUNK_SIZE]}
    if index == 0:
        payload["candidates"] = corpus["candidates"]
    (DATA / f"vocab-part-{index}.js").write_text(
        "// Generated by tools/build-runtime-data.py from data/learning-data.js.\n"
        "window.MANCHAI_VOCAB_PARTS=window.MANCHAI_VOCAB_PARTS||[];"
        f"window.MANCHAI_VOCAB_PARTS[{index}]="
        + json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )
print(f"Built page-specific course and code data, plus {index + 1} vocabulary parts.")
