"""Build the 24-key shape reference from the reviewed CSV and code corpus."""

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
source = (DATA / "learning-data.js").read_text(encoding="utf-8")
codes = json.loads(source.split("window.MANCHAI_DATA=", 1)[1].rstrip(";\n"))["codes"]
roots = dict(zip("ABCDEFGHIJKLMNOPQRSTUVWY", "日月金木水火土竹戈十大中一弓人心手口尸廿山女田卜"))
groups = [
    ("哲理類", "ABCDEFG"),
    ("筆劃類", "HIJKLMN"),
    ("人身類", "OPQR"),
    ("字形類", "STUVWY"),
]
guide = {key: {"key": key, "root": root, "shapes": []} for key, root in roots.items()}
seen = set()
with (DATA / "root-guide.csv").open(encoding="utf-8", newline="") as source_file:
    for row in csv.DictReader(source_file):
        key, shape, example = row["key"], row["shape"], row["example"]
        direct = row["direct"] == "True"
        if key not in guide or shape in seen or len(example) != 1:
            raise ValueError(f"Invalid root-guide row: {row}")
        if not (ROOT / "assets/root-shapes" / f"{shape}.png").is_file():
            raise ValueError(f"Missing shape drawing: {shape}")
        full = codes.get(example)
        if not full or key not in full:
            raise ValueError(f"Example {example} does not use key {key}")
        guide[key]["shapes"].append({
            "id": shape, "example": example, "direct": direct, "full": full,
            "quick": full if len(full) == 1 else full[0] + full[-1],
        })
        seen.add(shape)
if len(seen) != 191 or guide["R"]["shapes"]:
    raise ValueError("Expected all 191 auxiliary drawings and no R variants")
for group, keys in groups:
    for key in keys:
        guide[key]["group"] = group
payload = [guide[key] for key in roots]
(DATA / "root-guide-data.js").write_text(
    "// Generated by tools/build-root-guide.py from data/root-guide.csv.\n"
    "window.MANCHAI_ROOT_GUIDE=" + json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + ";\n",
    encoding="utf-8",
)
print(f"Built {len(payload)} root entries and {len(seen)} auxiliary shape examples.")
