"""Build local stroke drawings with conservative Cangjie component highlights.

Source: skishore/makemeahanzi bddc96d41bef78427ed0e034e9f7e31d71fd1b92.
Geometry: Arphic Public License; component metadata: LGPL-3.0-or-later.
An unknown endpoint is left uncoloured; never approximate it with a clipping box.
"""

import csv
import json
import re
from pathlib import Path
from xml.sax.saxutils import quoteattr

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
ASSETS = ROOT / "assets/glyphs"
COMPONENTS = {x["character"]: x for x in map(json.loads, (DATA / "glyph-source/components.ndjson").read_text().splitlines())}
GRAPHICS = {x["character"]: x["strokes"] for x in map(json.loads, (DATA / "glyph-source/strokes.ndjson").read_text().splitlines())}
RULES = {}
for row in csv.DictReader((DATA / "glyph-components.csv").open()):
    RULES[(row["component"], row["side"], row["key"])] = row
OPS = {c: 2 for c in "⿰⿱⿴⿵⿶⿷⿸⿹⿺⿻"} | {"⿲": 3, "⿳": 3}


def parse_ids(text):
    chars = iter(text)
    def node():
        char = next(chars)
        return (char, [node() for _ in range(OPS[char])]) if char in OPS else char
    return node()


def endpoint(character, side, key, indices=None, parents=()):
    if character in parents:
        return None
    metadata = COMPONENTS.get(character)
    if indices is None:
        if not metadata:
            return None
        indices = list(range(len(metadata["matches"])))
    rule = RULES.get((character, side, key))
    if rule:
        if rule["strokes"] == "all":
            return indices
        if int(rule["count"]) == len(indices):
            return [indices[int(i)] for i in rule["strokes"].split()]
    if not metadata or len(metadata["matches"]) != len(indices):
        return None
    tree = parse_ids(metadata["decomposition"])
    if isinstance(tree, str):
        return None
    def descend(node, path):
        if isinstance(node, str):
            group = [indices[i] for i, match in enumerate(metadata["matches"]) if match == path]
            return endpoint(node, side, key, group, parents + (character,)) if group else None
        child = 0 if side == "first" else len(node[1]) - 1
        return descend(node[1][child], path + [child])
    return descend(tree, [])


course = json.loads((DATA / "lesson-data.js").read_text().split("window.MANCHAI_DATA=", 1)[1].rstrip(";\n"))
characters = {char: code for chapter in course["chapters"] for char, code in chapter["entries"]}
characters.update(dict(re.findall(r'\["(.)","([A-Z]+)"', (ROOT / "script.js").read_text())))
reading = json.loads((DATA / "reading-data.js").read_text().split("window.MANCHAI_READING=", 1)[1].rstrip(";\n"))
codes = json.loads((DATA / "code-data.js").read_text().split("window.MANCHAI_DATA=", 1)[1].rstrip(";\n"))["codes"]
for lesson in reading["sentences"] + reading["paragraphs"]:
    for character in lesson["text"]:
        full = codes.get(character) or reading["codeHints"].get(character, [None])[0]
        if full:
            characters.setdefault(character, full)
ASSETS.mkdir(exist_ok=True)
manifest = {}
for character, code in sorted(characters.items()):
    strokes = GRAPHICS.get(character)
    if not strokes:
        continue
    first = endpoint(character, "first", code[0]) or []
    last = endpoint(character, "last", code[-1]) or []
    single = len(code) == 1
    if single:
        first, last = list(range(len(strokes))), []
    elif set(first) & set(last):
        # A shared stroke needs an explicit contextual rule, not an arbitrary colour.
        last = []
    assert all(0 <= index < len(strokes) for index in first + last)
    roles = {"first": first, "last": last, "ink": [i for i in range(len(strokes)) if i not in first + last]}
    parts = []
    for role, indices in roles.items():
        paths = "".join(f"<path d={quoteattr(strokes[i])}/>" for i in indices)
        parts.append(f'<g id="{role}" transform="translate(0 900) scale(1 -1)">{paths}</g>')
    name = f"{ord(character):x}.svg"
    (ASSETS / name).write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024"><defs>' + "".join(parts) + '</defs></svg>')
    manifest[character] = [code, bool(first), bool(last), single]

copy = {row["key"]: row["zh-HK"] for row in csv.DictReader((DATA / "diagram-copy.csv").open())}
(DATA / "diagram-data.js").write_text(
    "// Generated by tools/build-glyph-diagrams.py; edit CSV sources instead.\n"
    + "window.MANCHAI_DIAGRAMS=" + json.dumps({"glyphs": manifest, "copy": copy}, ensure_ascii=False, separators=(",", ":")) + ";\n"
)
complete = sum(bool(row[1] and (row[2] or row[3])) for row in manifest.values())
partial = sum(bool(row[1] or row[2]) and not (row[1] and (row[2] or row[3])) for row in manifest.values())
print(f"Built {len(manifest)} local stroke drawings: {complete} with both endpoints, {partial} with one endpoint.")
