"""Generate chat UI and server context from editable CSV sources."""
import csv, html, json, re
from pathlib import Path
root=Path(__file__).resolve().parent.parent

def rows(name):
    with (root/'data'/f'chat-{name}.csv').open(encoding='utf-8',newline='') as f:
        return list(csv.DictReader(f))
copy_rows=rows('copy')
assert len({r['key'] for r in copy_rows})==len(copy_rows)
copy={r['key']:r['zh-HK'] for r in copy_rows}
assert all(copy.values())
games=rows('games')
scenarios=rows('scenarios')
assert len({g['id'] for g in games})==len(games)
assert len({(s['game'],s['id']) for s in scenarios})==len(scenarios)
for game in games:
    game['replies']=json.loads(game['replies'])
    game['scenarios']=[{k:v for k,v in s.items() if k!='game'} for s in scenarios if s['game']==game['id']]
    assert len(game['scenarios'])==3 and len(game['replies'])==3
    assert re.fullmatch(r'#[0-9a-f]{6}',game['color'])
tones=rows('tones')
data={'copy':copy,'games':games,'tones':tones}
serialized=json.dumps(data,ensure_ascii=False,separators=(',',':'))
(root/'data/chat-data.js').write_text('// Generated by tools/build-chat.py; edit data/chat-*.csv.\nwindow.MANCHAI_CHAT='+serialized+';\n',encoding='utf-8')
(root/'worker/chat-data.mjs').write_text('// Generated by tools/build-chat.py; edit data/chat-*.csv.\nexport default '+serialized+';\n',encoding='utf-8')
template=(root/'templates/chat.html').read_text(encoding='utf-8')
page=re.sub(r'\{\{([\w.-]+)\}\}',lambda m:html.escape(copy[m[1]],quote=True),template)
(root/'chat.html').write_text('<!-- Generated by tools/build-chat.py; edit templates/chat.html and data/chat-*.csv. -->\n'+page,encoding='utf-8')
print(f'Built chat page, {len(games)} games, {len(scenarios)} scenarios and {len(copy)} translations.')

# Keep the new navigation label sourced from CSV on every existing page.
link='<a href="chat.html" data-chat-nav="true">'+html.escape(copy['nav.chat'])+' <span class="nav-beta">'+html.escape(copy['beta'])+'</span></a>'
for name in ('index.html','learn.html','roots.html','practice.html'):
    path=root/name
    content=path.read_text(encoding='utf-8')
    content=re.sub(r'<a href="chat.html" data-chat-nav="true">.*?</a>', '', content)
    content=re.sub(r'(<nav class="main-nav"[^>]*>)(.*?)(</nav>)', lambda m:m[1]+m[2].rstrip()+link+m[3], content, flags=re.S)
    path.write_text(content,encoding='utf-8')
