"""Generate the beginner tutor's UI translations from editable CSV."""
import csv
import json
from pathlib import Path

data = Path(__file__).resolve().parent.parent / "data"
for name in ("practice", "progress"):
    rows = list(csv.DictReader((data / f"{name}-copy.csv").open(encoding="utf-8")))
    assert len({row["key"] for row in rows}) == len(rows), "Duplicate translation keys"
    assert all(row["key"] and row["zh-HK"] for row in rows), "Empty translation"
    (data / f"{name}-copy.js").write_text(
        f"// Generated by tools/build-practice-copy.py; edit data/{name}-copy.csv.\n"
        + f"window.MANCHAI_{name.upper()}_COPY="
        + json.dumps({row["key"]: row["zh-HK"] for row in rows}, ensure_ascii=False, separators=(",", ":"))
        + ";\n", encoding="utf-8")
    print(f"Built {len(rows)} {name} translations.")
